package kanagawa.models.enums;

public enum UvName {
    // CS COMP_SCI
    ARTIFICIAL_INTELLIGENCE,
    OBJECT_ORIENTED_PROGRAMMING,
    // TM COMP_SCI
    JAVA_ENTERPRISE,
    DATA_SCIENCE,
    // CS MECHANICS
    ORGANIC_MATERIALS,
    NUMERICAL_ANALYSIS,
    // TM MECHANICS
    ENVIRONMENT_CONCEPTION,
    MECHATRONIC_SYSTEMS,
    // CS ENERGY
    ELECTRONIC_MACHINES,
    THERMODYNAMICS,
    // TM ENERGY
    ENERGY_STORAGE,
    RENEWABLE_ENERGY,
    // CS INDUSTRY
    AUTOMATED_SYSTEMS,
    OPERATIONS_MANAGEMENT,
    // TM INDUSTRY
    TECHNICAL_CREATIVITY,
    INDUSTRIAL_ROBOTICS,

    // OM FOR ALL
    ORGANISATIONS_SOCIOLOGY,
    ORAL_EXPRESSION,
    ECONOMY_GLOBALIZATION,
    JURIDICAL_KNOWLEDGE,

    // EC FOR ALL
    BUSINESS_ENGLISH,
    ENGLISH_LEVEL_3,
    SPANISH_LEVEL_1,
    JAPANESE_FOR_BEGINNERS;
}
